### ISSUE TITLE
Converter uses CdbReader instance after CdbReader shutdown

### ISSUE THREAD

**Issue by msekoranja** [IntegratedAlarmSystem-Group/ias#181]
Converter calls getIasios() method on CdbReader instance after CdbReader.shutdown() is being called.

**Comment by acaproni** [comment]
Great finding Matej
Can I ask you to please submit tickets instead of emails? I miss emails from time to time but not the tickets 😉
This error never showed up because JSON reader shutdown does nothing. It matters with RDM implementation instead and maybe with CII lib.

Thanks,
Ale

**Comment by acaproni** [comment]
Ops.. I just found the tickets! Very god thank you a lot.

Ale


From: Alessandro Caproni
Sent: 02 April 2020 11:29
To: 'IntegratedAlarmSystem-Group/ias' <reply@reply.github.com>
Subject: RE: [IntegratedAlarmSystem-Group/ias] Converter uses CdbReader instance after CdbReader shutdown (#181)

Great finding Matej
Can I ask you to please submit tickets instead of emails? I miss emails from time to time but not the tickets 😉
This error never showed up because JSON reader shutdown does nothing. It matters with RDM implementation instead and maybe with CII lib.

Thanks,
Ale

**Comment by acaproni** [comment]
As Matej correctly spotted the constructor of the `Converter` shuts the `CdbReader` that will be used later on during initialization.
