### ISSUE TITLE
DASU processing input time bug

### ISSUE THREAD

**Issue by cristobal-vildosola** [IntegratedAlarmSystem-Group/ias#49]
While running a DASU i got the following exception
`KafkaSubscriber - Subscriber of DASU [DasuTemp2] got an error processing event [IASValueBase: ...]`
`java.lang.IllegalArgumentException: requirement failed: Invalid execution time`
`at scala.Predef$.require(Predef.scala:277)`
`at org.eso.ias.dasu.TimeScheduler.getNextRefreshTime(TimeScheduler.scala:135)`

reviewing the code i found the line that throws this exception is
`def getNextRefreshTime(lastExecTime: Long): Int = {`
    `require(Option(lastExecTime).isDefined && lastExecTime>0,"Invalid execution time")`
    ...

where lastExecTime is a time difference calculated here
`val before = System.currentTimeMillis()`
`val newOutput = propagateIasios(notYetProcessedInputs.values.toSet)`
`val after = System.currentTimeMillis()`
...
`timeScheduler.getNextRefreshTime(after-before)`

Assuming the variable is defined (System.currentTimeMillis() is pretty standard), it must be less than or equal to 0 to raise the exception. Then, the error could be that the processing is taking less than 1 millisecond, this is possible as my DASU is running only 1 ASCE with a simple threshold function, only a couple of instructions are executed.

2 possible fixes i can think about are
1. changing the condition to >= 0.
2. changing the measure to microseconds.

but i'm not sure if thats the answer, maybe my analysis is incorrect.

**Comment by acaproni** [comment]
Thank for reporting the bug, Cristobal.

To double check, could you let the require report the time by changing 
`require(Option(lastExecTime).isDefined && lastExecTime>0,"Invalid execution time")` 
to something like
`require(Option(lastExecTime).isDefined && lastExecTime>0,"Invalid execution time: "+lastExecTime)`

**Comment by cristobal-vildosola** [comment]
just tested it, the output is 0 as i thought.
`java.lang.IllegalArgumentException: requirement failed: Invalid execution time: 0
	at scala.Predef$.require(Predef.scala:277)`

**Comment by acaproni** [comment]
Cristobal.. my laptop and desktop must be so slow that I never met this case: very good that you met it before deploying the software in a super warp speed server.

The failing method (thanks for the good investigation) try to guess the best point in future to update the output if no input has been received assuming that the last execution time was positive (that it is not the case according to your test).
There is no point to switch to microsecond because we do not need such a precision so I would relax the check as you suggested initially.
We should also check if a value of 0 could trigger some unforeseen problem (div by 0?) in the algorithm.
If have time, could you change the require to `>=0`, check the algorithm and re-run your test just to be sure?

If works please commit in the develop branch mentioning this issue (#49) in the comment.

I´ll assign this ticket to you, if have no time just reassign to my.

**Comment by cristobal-vildosola** [comment]
Just committed the change, ran a demo for some minutes and didn't get any new exception or error so it looks like it works okay with exectime 0.

**Comment by acaproni** [comment]
Good job, thank you!
