### ISSUE TITLE
DASU output is not reflecting timestamp and mode from input

### ISSUE THREAD

**Issue by cristobal-vildosola** [IntegratedAlarmSystem-Group/ias#52]
After running the plugin, converter, dasu, and display, we noticed the timestamp and the operational mode in the dasu output were not taking the timestamp and operational mode from the input.

The following input:
```
{
  "value": "5.659",
  "tStamp": 1516218517895,
  "mode": "OPERATIONAL",
  "iasValidity": "RELIABLE",
  "fullRunningId": "(WeatherStationSystem:MONITORED_SOFTWARE_SYSTEM)@(WeatherStationPlugin:PLUGIN)@(KafkaConverterId:CONVERTER)@(Temperature2:IASIO)",
  "valueType": "DOUBLE"
}
```
generated this output:
```
{
  "value": "CLEARED",
  "tStamp": 1516218416151,
  "mode": "UNKNOWN",
  "iasValidity": "RELIABLE",
  "fullRunningId": "(DasuTemperature2:DASU)@(AsceTemperature2:ASCE)@(AlarmTemperature2:IASIO)",
  "valueType": "ALARM"
}
```
the output never changed, and we verified that the input was changing constantly, according to the plugin generation of values.

Apparently, the dasu/asce is taking the timestamp of its creation and putting it in the alarm output, leaving it invalid.

**Comment by acaproni** [comment]
The timestamp of the output is the timestamp of the creation time of the output by the DASU (actually the TF of the ASCE running in the DASU) it is unrelated to the timestamp of the monitor point generated by the plugin.

The operational mode is the default one. If you are using the TF then IMO that transfer function should get and propagate the operational mode of the monitor point read by the monitored system.
For more comlex cases (like a TF that generates the output using several monitor points) then the TF msu decide how to set the operational mode.

Actually, it probably make sense to offer a method that sets the operational mode to the lowest operational mode of a set of AISValue that could be reused in the TF

**Comment by acaproni** [comment]
According to Cristobal, the DASU does not set the timestamp when resending the output unless the value changed

**Comment by cristobal-vildosola** [comment]
After testing with a dummy value, the alarm timestamp only changes after the value changed. If the value of the alarm doesn't change, the timestamp remains the same even though the input timestamp constantly changes.
![this image](https://user-images.githubusercontent.com/26608721/35066280-d82178a4-fbae-11e7-9995-c0150019c2b4.png) shows the behavior explained above.

**Comment by acaproni** [comment]
Yesterday we agreed to 
* fix the timstamp
* autotically update the mode on the lower mode of set of IASIOs in input to the DASU but allow the user to override in the TF.

**Comment by acaproni** [comment]
The DASU is in charge of refreshing the output by means of a timer task that trigger the execution of the TF in the ASCEs.
The `InOut` provides methods to update the value, the mode and the validity that trigger the build of a new object (the `InOut` is immutable). To reduce the number of objects built at run-rime a new object is returned only if the value, mode or validity changes otherwise the same object is returned.

This matches with Cristobal´s investigation: if the value of the `InOut` changes then a new object (with a new timestamp) is returned otherwise the timestamp remains unchanged.

**Comment by acaproni** [comment]
Rethinking about the way the validity and automatic refresh should be done:

* automatic refresh happens when there are no new inputs (i.e. the TF runs with an empty `Set()` of inputs: in this case only the validity of the output must be refreshed depending on the validity of the (old) inputs: If the validity changes then also the timestamp of the output changes
* if there are new inputs the output is evaluated again with the TF and the timestamp must always be updated (i.e even when the TF did not change the value of the output)

**Comment by jmaldonadof** [comment]
About the timestamp, we agree with the solution proposed. With that solution we can update the validity in the GUIs considering the timestamp of the DASU's output.

About the refresh rate, currently the plugin is using the refresh rate as the sending time interval and it updates the value every second. This update triggers a sending of the updated value, besides the automatic resend every refresh rate. We can modify the plugin to use the global property to define the sending time interval and use the refresh rate to update the values. 

Set the default sending time interval in 5 seconds seems good, but it is important to take in account that depending on the case, another value should be defined because the sending time interval must be less than or equal to the refresh rate.

**Comment by acaproni** [comment]
Yes Jazmine, it will be possible to tune the time interval globally or for each tool (plugin, DASU).

**Comment by acaproni** [comment]
In this implementation the default auto refresh time interval is set to 5 seconds and customizable by setting the `ias.supervisor.autosend.time` java property (seconds) while running the supervisor.

Adding the auto refresh time in the global IAS configuration will be implemented in the scope of #54

**Comment by acaproni** [comment]
The timestamp of the output generated by the DASU is now updated if any of its field changes i.e. validity, mode, value. 
When the output is sent periodically, the last computed value is sent untouched. In particular its validity is not updated from expected refresh rates of the output itself and its inputs.

The rule to implement is that the validity o the output is 
* the lowest validity of its inputs
* invalid if the output itself has not been refreshed in time

Same logic must be implemented in the plugin.

**Comment by acaproni** [comment]
Found and fixed a bug in `InOut.update(iasValue: IASValue[_])` that was not setting the mode of the `IASValue` in the `InOut`. This could explain the second part of this ticket.

**Comment by acaproni** [comment]
What I said yesterday is not quite correct because updading the timestamp when updating the validity would make a IASIOs always valid.
The validity must always be calculated because it depends on
* the actual timestamp against the last update time and the refresh rate
* the min validity of the IASIOs in input to the TF that generates a IASIOs, if the IASIOs is generated by a ASCE.

Note that the validity is not a property of a IASIOs but returned by a method that makes the calculation.

The IASValue published in the BSDB will have the validity calculated at the moment of the conversion from a IASIOs. However, before using the value, its validity must again be validated against the actual timestamp.

**Comment by acaproni** [comment]
The validity must always be calculated because it depends on
* the actual timestamp against the last update time and the refresh rate
* the min validity of the IASIOs in input to the ASCE (if the IASIOs is generated by a ASCE): must also be evaluated against the actual timestamp
* the validity provided by BSDB (i.e. that received as part of the `IASValue` 

So there 3 factors to take into account, 2 of them need to be evaluated when the validity of a monitor point is needed. For this reason the validity is not a property of a IASIOs but returned by a method that makes the calculation.

The IASValue published in the BSDB has a validity calculated that is the validity of the value at the moment of the conversion from a IASIOs i.e. when it is sent to the BSDB. However, before using the value, its validity must again be validated against the actual timestamp and other factors as described.

The validity received by the `IASValue` is part of the IASIOs and will be refreshed when an update is consumed from the BSDB. IASIOs produced by TFs does not have this validty as they do not come from the BSDB; however IASIOs produced by TF will set the validity in the `IASValue` that will be published in the BSDB.

**Comment by acaproni** [comment]
The fix has been committed in the `fix-dasu-output-Issue#52` feature branch. Needs some more testing before being merged in the develop branch.

**Comment by cristobal-vildosola** [comment]
Gonna test that the DASU output keeps the validity updated and uses the operational mode of the input. I'll use an ASCE with only one input, so i won't be able to check it takes the minimum validity from it's input. Still, it should be good enough for the demo if it works.

**Comment by acaproni** [comment]
Just opened #58 to unify auto-sending and validity for the plugins.

**Comment by cristobal-vildosola** [comment]
Just finished testing, the timestamp is updating ok but the following things are missing:
* The output is not taking the operational mode from the input, it still takes the default UNKNOWN mode.
* The output is not checking the iasValidity from the input. Even when the input has validity unreliable the output is reliable.
These 2 things can be apreciated in the following picture.
![image](https://user-images.githubusercontent.com/26608721/35454973-063561d6-02af-11e8-9e53-9450bca19f61.png)


Another error is that the unit in the Supervisor variable RefreshTimeIntervalMSecs is wrong. It is using Microseconds while the dasu is measuring time in milliseconds. line 353 should be changed accordingly.

That's all i could find.

**Comment by cristobal-vildosola** [comment]
Forgot to mention that the automatic resending is working too, and marks the output unreliable as it was expected.

**Comment by acaproni** [comment]
Cristobal thanks a lot for testing. If I get it right, the alarm produced by the DASU is not taking into account the validity and mode coming from the plugin.

I assume that timestamps are updated as expected. And that after awhile the autosend makrs the alarm as invalid.

**Comment by cristobal-vildosola** [comment]
yes, the timestamp updates every time a new output is generated, and after the input stops the outputs is marked invalid.

**Comment by acaproni** [comment]
I tested the plugin by customizing the example in the plugin/test and double checked that both mode and validity are correctly sent to the BSDB:

```
{"sampleTime":"2018-01-29T10:38:01.437","filteredTime":"2018-01-29T10:38:01.438","value":"0.020204959078882867","id":"Temperature","operationalMode":"MAINTENANCE","validity":"UNRELIABLE"},
...
{"sampleTime":"2018-01-29T10:27:41.103","filteredTime":"2018-01-29T10:27:41.103","value":"-27.41459871758967","id":"WindSpeed","operationalMode":"UNKNOWN","validity":"RELIABLE"},
...
```

The Converter correctly translates the mode and reliability:

```
{"sampleTime":"2018-01-29T11:59:32.175","filteredTime":"2018-01-29T11:59:32.176","value":"129.98687203908884","id":"WindDirection","operationalMode":"STARTUP","validity":"RELIABLE","pluginID":"WeatherStation-plugin","monitoredSystemID":"WeatherStation","publishTime":"2018-01-29T11:59:32.673"}
```

By adding Supervisor, DASUs and ASCEs I found that the operational mode produced by the ACS is not up to date:
```
{"value":"162.45135042108538","tStamp":1517240962035,"mode":"OPERATIONAL","iasValidity":"RELIABLE","fullRunningId":"(WeatherStation:MONITORED_SOFTWARE_SYSTEM)@(WeatherStation-plugin:PLUGIN)@(CONVERTER_ID:CONVERTER)@(WindDirection:IASIO)","valueType":"DOUBLE"}
{"value":"CLEARED","tStamp":1517240962692,"mode":"UNKNOWN","iasValidity":"RELIABLE","fullRunningId":"(SupervisorID:SUPERVISOR)@(DasuWindSpeed:DASU)@(AsceWindSpeed:ASCE)@(WindSpeedAlarm:IASIO)","valueType":"ALARM"}
```

The reason is that the ASCE does not take into account the operational mode of its inputs: we should let the TF be able to set the mode or, if not invoked, inherit the operational mode of the inputs. but which one if a TF receives more then one input?

The second problem is that after killing the plugin, when no new inputs arrive to the DASU, it does not refresh the output

**Comment by acaproni** [comment]
The missing refresh rate of the DASu is due to a wrong time interval:

```
13:13:56.948 [main] INFO  org.eso.ias.dasu.DasuImpl [DasuImpl.scala:428] - DASU [DasuTemp]: automatic refresh of output enabled at intervals of 5000000 msecs (aprox)
13:13:56.949 [main] INFO  org.eso.ias.dasu.DasuImpl [DasuImpl.scala:428] - DASU [DasuWindSpeed]: automatic refresh of output enabled at intervals of 5000000 msecs (aprox)
```

There was a bug in the Supervisor while converting seconds to millisecond (it was passing mcorseconds)/

**Comment by acaproni** [comment]
I would say that the implementation of TF that produces IASIO should also correctly set the operational mode. I updated the MinMaxTF provided by the IAS to innject the operationan mode of its only one input in the ouput.

More complex TF, evaluating more inputs, should set the operational mode according to their heuristic. The IAS will provide support methods when needed.

After the fix, the operational mode is updated:
```
{"value":"CLEARED","tStamp":1517244421073,"mode":"STARTUP","iasValidity":"RELIABLE","fullRunningId":"(SupervisorID:SUPERVISOR)@(DasuWindSpeed:DASU)@(AsceWindSpeed:ASCE)@(WindSpeedAlarm:IASIO)","valueType":"ALARM"}
```

**Comment by cristobal-vildosola** [comment]
Alessandro there's still one point left, this were the errors i listed in an earlier comment

- [x] The output is not taking the operational mode from the input, it still takes the default UNKNOWN mode.
- [ ] The output is not checking the iasValidity from the input. Even when the input has validity unreliable the output is reliable.
- [x] Another error is that the unit in the Supervisor variable RefreshTimeIntervalMSecs is wrong. It is using Microseconds while the dasu is measuring time in milliseconds. line 353 should be changed accordingly.

The output from the DASU is still marked as RELIABLE although the plugin input is marked as UNRELIABLE. I think this might be a problem in the TransferFunction but it shouldn't depend on the specific ThresholdTF we are using. 
If an input is marked as unreliable maybe it could be ignored by the DASU, and let the automatic refresh mark the output as invalid, or it could check all its inputs are reliable and set its validity accordingly.

**Comment by acaproni** [comment]
Cristobal, did you test with the latest version in the develop branch? I think this issue has been fixed as well but would be nice to check it again. I am planning to start writing some integration test to check data flow from plugins to the output generated by the DASU soon possibly after the DEMO.
In the mean time we can keep this issue open until 100% sure that have fixed all the oproblems
Thank you for spotting.

Aside note: the DASUs run the TF even if some of the inputs are not reliable  because other might be reliable. The idea is to let the DASU continuously produce alarms as "best effort" but marking them as unreliable, if it is the case. Does it sounds reasonable?

**Comment by cristobal-vildosola** [comment]
Yes, I'm in develop and up to date. I'm 100% sure the DASU output is not taking in account the iasvalidity of its input, as you can see in this image.
![image](https://user-images.githubusercontent.com/26608721/35533459-64e75ce2-051c-11e8-890a-79b0b086b07b.png)
I'm not sure where you can fix this, but it is definetively a problem.

**Comment by acaproni** [comment]
Yes Cristobal, you´re right. I will look at it, thank you.

**Comment by acaproni** [comment]
A new version with update validity calculation has been committed in the `feature/fix-dasu-output-Issue#52` that should hopefully fix the validity issue.

The validity is calculated following the algorithm described last [25/01/2018](https://github.com/IntegratedAlarmSystem-Group/ias/issues/52#issuecomment-360594882).

**Comment by acaproni** [comment]
It should be ok now. I tested with Cristobal´s [DummyPlugin](https://github.com/IntegratedAlarmSystem-Group/ias-plugins/tree/master/DummyPlugin) ang got the following output in the BSDK kafka topic when forcing the validity of the input to UNRELIABLE:

```
{"value":"5.0","tStamp":1518089013948,"mode":"OPERATIONAL","iasValidity":"RELIABLE","fullRunningId":"(DummyStation:MONITORED_SOFTWARE_SYSTEM)@(DummyPlugin:PLUGIN)@(ConverterID:CONVERTER)@(dummy:IASIO)","valueType":"DOUBLE"}
{"value":"CLEARED","tStamp":1518089016216,"mode":"OPERATIONAL","iasValidity":"RELIABLE","fullRunningId":"(SupervisorDummy:SUPERVISOR)@(Dasudummy:DASU)@(Ascedummy:ASCE)@(Alarmdummy:IASIO)","valueType":"ALARM"}
{"value":"5.0","tStamp":1518089016448,"mode":"OPERATIONAL","iasValidity":"UNRELIABLE","fullRunningId":"(DummyStation:MONITORED_SOFTWARE_SYSTEM)@(DummyPlugin:PLUGIN)@(ConverterID:CONVERTER)@(dummy:IASIO)","valueType":"DOUBLE"}
{"value":"CLEARED","tStamp":1518089016701,"mode":"OPERATIONAL","iasValidity":"UNRELIABLE","fullRunningId":"(SupervisorDummy:SUPERVISOR)@(Dasudummy:DASU)@(Ascedummy:ASCE)@(Alarmdummy:IASIO)","valueType":"ALARM"}
```

Cristobal, do you have time for double checking before returning to your previous life?
The test should be done with the `feature/fix-dasu-output-Issue#52` branch installed.

**Comment by acaproni** [comment]
Merged in `develop`

**Comment by cristobal-vildosola** [comment]
just tested it, got the same results as Alessandro. I think this issue is finally ready to be closed :D

**Comment by acaproni** [comment]
Great, thanks a lot.

I close the ticket and prepare the release of the core.
