### ISSUE TITLE
There should be a property to define kafka servers specified in the arguments of iasRun in order to run the supervisor

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias#68]
When we run the supervisor with the iasRun there should be an argument to specify the kafka servers, to change the default server "localhost:9092".

The command should be something like this:

$ iasRun -l s -Dorg.eso.ias.[property]=IP:9092 org.eso.ias.converter.Converter ConverterID -jcdb CDB_FOLDER

Were [property] should be the property
Probably there is already a property defined for this purpose but it is not working.
We have tried the following with no luck:
- org.eso.ias.bootstrap.servers
- org.eso.ias.kafka.broker
- org.eso.ias.converter.kafka.servers

This is similar to the case of the converter. See issue [#67](https://github.com/IntegratedAlarmSystem-Group/ias/issues/67)

**Comment by acaproni** [comment]
I would add such a property to the IAS configuration of the [CDB](https://github.com/IntegratedAlarmSystem-Group/ias/wiki/ConfigurationDatabase).
All the IAS tools must be able to get the configuration from the CDB.

I cannot see a valid use-case to override the global configuration by passing a java property in the command line.
Do you have such a use case?

**Comment by sfehlandt** [comment]
Either on the CDB or through a property in the command line the idea is tonne able to distribute ias applications in a network if neede right? Right now the Supervisor is always specting Kafka to be running in localhost:9092.

One use case is this:
Kafka running in machine A
Supervisor running in machine B

Anyway. I would stick to your original idea, which is the properties assignable though arguments. This is already implemented for the other components (Converter, WenserverSender). Moreover. Since this is mostly a deployment configuration I would keep it apart from the CDB. This way you decouple deployment parameters from CDB, making your whole application deployment-agnostic.

Furthermore, I think this is supposed to be already implemented in the supervisor, just like it is already working for the Converter. I believe it is only a bug. At some point the parameter is b una ignored and the DEFAULT parameter is beinng used instead.

**Comment by acaproni** [comment]
It is practical and less error prone, to have the Kafka servers list in the CDB.
The same servers list accessed by all the core tools not only by the Supervisor. For example the Converters, kafka listeners of KafkUtils, other clients. Having the servers list in the CDb ensure to update all the tools by fixing only the entry of the CDB instead of having to change the command line of many scripts here and there.
By definition the CDB is available to all IAS tools (apart the plugins).

IAS configuration allows to set user properties in the form <name, value> but at the present it is ignored:
I will fix this part.

So, the Supervisor (and all other IAS core tool):
* get the list of kafka servers from java properties
* otherwise from CB (AIS table)
* otherwise use default

**Comment by acaproni** [comment]
To reduce dependencies with the transport mechanism it is not convenient to have a column like `KAFKA_SERVERS` in the `IAS` table. If in future we want to replace kafka with something else, we will have to change the tables and the CDB.
A more generic alternative is to set the properties in the properties of the `IAS` table.
According to the [CDB wiki page](https://github.com/IntegratedAlarmSystem-Group/ias/wiki/ConfigurationDatabase), the IAS table contains PROPS defined as `list of user defined properties in the form <name, value>`.

Each IAS core tool should get the properties of the IAS following and merge them into the `System.properties`  following the schema reported last week:
* get the properties from the java properties in the command line
* otherwise get the properties from the CDB
* otherwise use the default

The easiest solution is to merge the properties from the IAS table of the CDB first and then from the command line into the `System.properties`.

For the implementation, a class providing the merge will be provided in `Tools`module and used by all the IAS core tools.

**Comment by sfehlandt** [comment]
This approach sound good, because you can override CDB configuration based on arguments to iasRun. This allows for quick changes in deployment without need to make changes in databases, or worst, code. Making the application independent of deployment :)

**Comment by acaproni** [comment]
Requires #62 to be fixed first.

**Comment by sfehlandt** [comment]
I disagree, actually we (I mean we at Inria Chile) are only using iasRun, we do not need the other commands. If you want to address #62, i think this issue (#63) should be fixed first, because #62 would only be a wrapper for iasRun instructions...

**Comment by acaproni** [comment]
We actually decided to not use iasRun as it shows implementation details like the package and name of the java/scala classes  to run. This is the ratio of #62.

It might not be clear to me how urgent is this ticket for you guys.

**Comment by acaproni** [comment]
The supervisor uses a `KafkaPublisher` defined in the DASU passing the System.properties that instantiates a `KafkaIasiosProducer` ignoring the passed properties. So, in the scope of this ticket we should fix this part to get the servers list from the properties if it exists.

the case of the `KafkaSubscriber` is simmetric.

**Comment by acaproni** [comment]
Sebastian could you test the changes?
You need first to build the core from this branch (`feature/kafka-server-properties-Issue#68`) and then to launch the supervisor with `iasRun` setting the `org.eso.ias.kafka.brokers` java properties

**Comment by acaproni** [comment]
Sebastian, no need to further testing as I already tested it with kafka running remotely on pc017892 and it works.
From the logs:
```
16:14:57.657 [main] INFO  o.e.i.d.subscriber.KafkaSubscriber [KafkaSubscriber.scala:99] - Initializing subscriber of DASU [SupervisorWithKafka]
16:14:57.689 [main] INFO  o.a.k.c.consumer.ConsumerConfig [AbstractConfig.java:223] - ConsumerConfig values:
        auto.commit.interval.ms = 1000
        auto.offset.reset = latest
        bootstrap.servers = [pc017892:9092]
...
16:14:57.691 [main] DEBUG o.a.k.clients.consumer.KafkaConsumer [LogContext.java:177] - [Consumer clientId=consumer-1, groupId=SupervisorWithKafka-GroupID] Initializing the Kafka consumer
16:14:58.093 [main] DEBUG org.apache.kafka.clients.Metadata [Metadata.java:270] - Updated cluster metadata version 1 to Cluster(id = null, nodes = [pc017892:9092 (id: -1 rack: null)], partitions = [])
...
16:14:58.171 [main] DEBUG o.a.k.clients.consumer.KafkaConsumer [LogContext.java:177] - [Consumer clientId=consumer-1, groupId=SupervisorWithKafka-GroupID] Kafka consumer initialized
16:14:58.171 [main] INFO  o.e.i.k.SimpleStringConsumer [SimpleStringConsumer.java:222] - Kafka consumer [SupervisorWithKafka] initialized
16:14:58.171 [main] INFO  o.e.i.d.subscriber.KafkaSubscriber [KafkaSubscriber.scala:102] - Subscriber of DASU [SupervisorWithKafka] intialized
16:14:58.172 [main] INFO  org.eso.ias.supervisor.Supervisor$ [Supervisor.scala:102] - Supervisor [SupervisorWithKafka] subscriber successfully initialized
```

Logs of the producer are very similar.
